name: APP CI
on: [push, pull_request]
jobs:
  pipeline:
    name: APP pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Build and publish docker image
        id: build-image
        env:
          IMG_REGISTRY: registrymkc.azurecr.io
          IMG_REPOSITORY: mkc-ranger-buddies-service
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v'))
        run: |
          GIT_TAG=${GITHUB_REF#refs/tags/}
          echo ${GIT_TAG}
          DOCKER_TAG=${GIT_TAG#refs/heads/master}
          echo ${DOCKER_TAG}
          DOCKER_TAG=${DOCKER_TAG#refs/heads/}
          echo ${DOCKER_TAG}

      - name: redeploy lab
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')
        run: |
          echo "completed test"